# Generated by Django 4.1.7 on 2023-03-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song_List', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='song',
        ),
    ]
