# Generated by Django 4.1.7 on 2023-03-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song_List', '0002_rename_title_song_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
