# Generated by Django 4.1.7 on 2023-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song_List', '0003_album_slug_artist_slug_song_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='song', max_length=100),
        ),
    ]
