# Generated by Django 4.1.7 on 2023-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song_List', '0005_alter_album_slug_alter_artist_slug_alter_song_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='song', max_length=100),
        ),
    ]
